/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspacesRouteImport } from './routes/_app.workspaces'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppWorkspaceNameRouteImport } from './routes/_app.workspace.$name'
import { Route as AppWorkspaceNameIndexRouteImport } from './routes/_app.workspace.$name.index'
import { Route as AppWorkspaceNamePapersRouteImport } from './routes/_app.workspace.$name.papers'
import { Route as AppWorkspaceNameNotesRouteImport } from './routes/_app.workspace.$name.notes'
import { Route as AppWorkspaceNameEvidenceRouteImport } from './routes/_app.workspace.$name.evidence'
import { Route as AppWorkspaceNameDatasetsRouteImport } from './routes/_app.workspace.$name.datasets'
import { Route as AppWorkspaceNameCitationsRouteImport } from './routes/_app.workspace.$name.citations'
import { Route as AppWorkspaceNameChatRouteImport } from './routes/_app.workspace.$name.chat'
import { Route as AppWorkspaceNamePaperPaperIdRouteImport } from './routes/_app.workspace.$name.paper.$paperId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceNameRoute = AppWorkspaceNameRouteImport.update({
  id: '/workspace/$name',
  path: '/workspace/$name',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceNameIndexRoute = AppWorkspaceNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceNameRoute,
} as any)
const AppWorkspaceNamePapersRoute = AppWorkspaceNamePapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => AppWorkspaceNameRoute,
} as any)
const AppWorkspaceNameNotesRoute = AppWorkspaceNameNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppWorkspaceNameRoute,
} as any)
const AppWorkspaceNameEvidenceRoute =
  AppWorkspaceNameEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => AppWorkspaceNameRoute,
  } as any)
const AppWorkspaceNameDatasetsRoute =
  AppWorkspaceNameDatasetsRouteImport.update({
    id: '/datasets',
    path: '/datasets',
    getParentRoute: () => AppWorkspaceNameRoute,
  } as any)
const AppWorkspaceNameCitationsRoute =
  AppWorkspaceNameCitationsRouteImport.update({
    id: '/citations',
    path: '/citations',
    getParentRoute: () => AppWorkspaceNameRoute,
  } as any)
const AppWorkspaceNameChatRoute = AppWorkspaceNameChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppWorkspaceNameRoute,
} as any)
const AppWorkspaceNamePaperPaperIdRoute =
  AppWorkspaceNamePaperPaperIdRouteImport.update({
    id: '/paper/$paperId',
    path: '/paper/$paperId',
    getParentRoute: () => AppWorkspaceNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/workspace/$name': typeof AppWorkspaceNameRouteWithChildren
  '/workspace/$name/chat': typeof AppWorkspaceNameChatRoute
  '/workspace/$name/citations': typeof AppWorkspaceNameCitationsRoute
  '/workspace/$name/datasets': typeof AppWorkspaceNameDatasetsRoute
  '/workspace/$name/evidence': typeof AppWorkspaceNameEvidenceRoute
  '/workspace/$name/notes': typeof AppWorkspaceNameNotesRoute
  '/workspace/$name/papers': typeof AppWorkspaceNamePapersRoute
  '/workspace/$name/': typeof AppWorkspaceNameIndexRoute
  '/workspace/$name/paper/$paperId': typeof AppWorkspaceNamePaperPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/workspace/$name/chat': typeof AppWorkspaceNameChatRoute
  '/workspace/$name/citations': typeof AppWorkspaceNameCitationsRoute
  '/workspace/$name/datasets': typeof AppWorkspaceNameDatasetsRoute
  '/workspace/$name/evidence': typeof AppWorkspaceNameEvidenceRoute
  '/workspace/$name/notes': typeof AppWorkspaceNameNotesRoute
  '/workspace/$name/papers': typeof AppWorkspaceNamePapersRoute
  '/workspace/$name': typeof AppWorkspaceNameIndexRoute
  '/workspace/$name/paper/$paperId': typeof AppWorkspaceNamePaperPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/_app/workspace/$name': typeof AppWorkspaceNameRouteWithChildren
  '/_app/workspace/$name/chat': typeof AppWorkspaceNameChatRoute
  '/_app/workspace/$name/citations': typeof AppWorkspaceNameCitationsRoute
  '/_app/workspace/$name/datasets': typeof AppWorkspaceNameDatasetsRoute
  '/_app/workspace/$name/evidence': typeof AppWorkspaceNameEvidenceRoute
  '/_app/workspace/$name/notes': typeof AppWorkspaceNameNotesRoute
  '/_app/workspace/$name/papers': typeof AppWorkspaceNamePapersRoute
  '/_app/workspace/$name/': typeof AppWorkspaceNameIndexRoute
  '/_app/workspace/$name/paper/$paperId': typeof AppWorkspaceNamePaperPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/dashboard'
    | '/settings'
    | '/workspaces'
    | '/workspace/$name'
    | '/workspace/$name/chat'
    | '/workspace/$name/citations'
    | '/workspace/$name/datasets'
    | '/workspace/$name/evidence'
    | '/workspace/$name/notes'
    | '/workspace/$name/papers'
    | '/workspace/$name/'
    | '/workspace/$name/paper/$paperId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/dashboard'
    | '/settings'
    | '/workspaces'
    | '/workspace/$name/chat'
    | '/workspace/$name/citations'
    | '/workspace/$name/datasets'
    | '/workspace/$name/evidence'
    | '/workspace/$name/notes'
    | '/workspace/$name/papers'
    | '/workspace/$name'
    | '/workspace/$name/paper/$paperId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/workspaces'
    | '/_app/workspace/$name'
    | '/_app/workspace/$name/chat'
    | '/_app/workspace/$name/citations'
    | '/_app/workspace/$name/datasets'
    | '/_app/workspace/$name/evidence'
    | '/_app/workspace/$name/notes'
    | '/_app/workspace/$name/papers'
    | '/_app/workspace/$name/'
    | '/_app/workspace/$name/paper/$paperId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$name': {
      id: '/_app/workspace/$name'
      path: '/workspace/$name'
      fullPath: '/workspace/$name'
      preLoaderRoute: typeof AppWorkspaceNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$name/': {
      id: '/_app/workspace/$name/'
      path: '/'
      fullPath: '/workspace/$name/'
      preLoaderRoute: typeof AppWorkspaceNameIndexRouteImport
      parentRoute: typeof AppWorkspaceNameRoute
    }
    '/_app/workspace/$name/papers': {
      id: '/_app/workspace/$name/papers'
      path: '/papers'
      fullPath: '/workspace/$name/papers'
      preLoaderRoute: typeof AppWorkspaceNamePapersRouteImport
      parentRoute: typeof AppWorkspaceNameRoute
    }
    '/_app/workspace/$name/notes': {
      id: '/_app/workspace/$name/notes'
      path: '/notes'
      fullPath: '/workspace/$name/notes'
      preLoaderRoute: typeof AppWorkspaceNameNotesRouteImport
      parentRoute: typeof AppWorkspaceNameRoute
    }
    '/_app/workspace/$name/evidence': {
      id: '/_app/workspace/$name/evidence'
      path: '/evidence'
      fullPath: '/workspace/$name/evidence'
      preLoaderRoute: typeof AppWorkspaceNameEvidenceRouteImport
      parentRoute: typeof AppWorkspaceNameRoute
    }
    '/_app/workspace/$name/datasets': {
      id: '/_app/workspace/$name/datasets'
      path: '/datasets'
      fullPath: '/workspace/$name/datasets'
      preLoaderRoute: typeof AppWorkspaceNameDatasetsRouteImport
      parentRoute: typeof AppWorkspaceNameRoute
    }
    '/_app/workspace/$name/citations': {
      id: '/_app/workspace/$name/citations'
      path: '/citations'
      fullPath: '/workspace/$name/citations'
      preLoaderRoute: typeof AppWorkspaceNameCitationsRouteImport
      parentRoute: typeof AppWorkspaceNameRoute
    }
    '/_app/workspace/$name/chat': {
      id: '/_app/workspace/$name/chat'
      path: '/chat'
      fullPath: '/workspace/$name/chat'
      preLoaderRoute: typeof AppWorkspaceNameChatRouteImport
      parentRoute: typeof AppWorkspaceNameRoute
    }
    '/_app/workspace/$name/paper/$paperId': {
      id: '/_app/workspace/$name/paper/$paperId'
      path: '/paper/$paperId'
      fullPath: '/workspace/$name/paper/$paperId'
      preLoaderRoute: typeof AppWorkspaceNamePaperPaperIdRouteImport
      parentRoute: typeof AppWorkspaceNameRoute
    }
  }
}

interface AppWorkspaceNameRouteChildren {
  AppWorkspaceNameChatRoute: typeof AppWorkspaceNameChatRoute
  AppWorkspaceNameCitationsRoute: typeof AppWorkspaceNameCitationsRoute
  AppWorkspaceNameDatasetsRoute: typeof AppWorkspaceNameDatasetsRoute
  AppWorkspaceNameEvidenceRoute: typeof AppWorkspaceNameEvidenceRoute
  AppWorkspaceNameNotesRoute: typeof AppWorkspaceNameNotesRoute
  AppWorkspaceNamePapersRoute: typeof AppWorkspaceNamePapersRoute
  AppWorkspaceNameIndexRoute: typeof AppWorkspaceNameIndexRoute
  AppWorkspaceNamePaperPaperIdRoute: typeof AppWorkspaceNamePaperPaperIdRoute
}

const AppWorkspaceNameRouteChildren: AppWorkspaceNameRouteChildren = {
  AppWorkspaceNameChatRoute: AppWorkspaceNameChatRoute,
  AppWorkspaceNameCitationsRoute: AppWorkspaceNameCitationsRoute,
  AppWorkspaceNameDatasetsRoute: AppWorkspaceNameDatasetsRoute,
  AppWorkspaceNameEvidenceRoute: AppWorkspaceNameEvidenceRoute,
  AppWorkspaceNameNotesRoute: AppWorkspaceNameNotesRoute,
  AppWorkspaceNamePapersRoute: AppWorkspaceNamePapersRoute,
  AppWorkspaceNameIndexRoute: AppWorkspaceNameIndexRoute,
  AppWorkspaceNamePaperPaperIdRoute: AppWorkspaceNamePaperPaperIdRoute,
}

const AppWorkspaceNameRouteWithChildren =
  AppWorkspaceNameRoute._addFileChildren(AppWorkspaceNameRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppWorkspaceNameRoute: typeof AppWorkspaceNameRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppWorkspaceNameRoute: AppWorkspaceNameRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
